project:
  type: book
  output-dir: "docs/"

book:
  title: "An (opinionated) introduction to R for biologists"
  subtitle: "Analysing qPCR and longitudinal data using R"
  author: "Carlos Ronchi"
  date: "2022-08-01"
  chapters:
    - index.qmd
    - chapters/preface.qmd
    - part: "First steps"
      chapters:
        - chapters/prerequisites.qmd
        - chapters/loading.qmd
        - chapters/cleaning.qmd
    - part: "Exploring"
      chapters:
        - chapters/preparing.qmd
        - chapters/plotting.qmd
    - part: "Modeling"
      chapters:
        - chapters/choosing.qmd
        - chapters/testing.qmd
    - part: "Wrap up"
      chapters:
        - chapters/reporting.qmd
    - chapters/conclusion.qmd
    - chapters/references.qmd
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Carlos Ronchi" 
    right: 
      - icon: github
        href: https://github.com/chronchi
      - icon: twitter 
        href: https://twitter.com/chronchi
  repo-url: https://github.com/chronchi/airb
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter]        

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

